site_name: East London Database
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    - navigation.path
    # - toc.integrate
    # - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: qmul # default # light mode
      primary: custom # indigo # header, sidebar, text links +
      accent: custom # purple # hovered links, buttons, scroll bars
  font:
    text: Source Sans Pro Regular
  # logo: img/CEG_logo.png
  favicon: img/favicon.ico

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.betterem # improved md formatting
  - pymdownx.caret # adds underline (^^) (& superscript (^)
  - pymdownx.mark # adds highlighting (==)
  - pymdownx.tilde # adds strikethrough (~)
  - pymdownx.details # collapsable sections (???)
  - pymdownx.superfences # nesting & custom fences 
  - pymdownx.highlight:
      anchor_linenums: true # code highlighting
  - pymdownx.inlinehilite # code highlighting
  - pymdownx.snippets # insert md or html snippets
  - admonition # callouts

copyright: |
  &copy; 2024 <a href="https://www.qmul.ac.uk/ceg/" target="_blank" rel="noopener">Clinical Effectiveness Group</a>

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.